In [ ]:
from pathlib import Path

import nba_on_court as noc
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 100)

if not hasattr(np, "in1d"):
    np.in1d = np.isin

In [91]:
#noc.load_nba_data(seasons=range(2020, 2026), data='nbastats', untar=True)
nbastats = pd.concat([pd.read_csv(x) for x in Path.cwd().glob('*.csv')], axis=0, ignore_index=True)

In [92]:
nbastats

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,22000001,2,12,0,1,7:07 PM,12:00,NaN,Start of 1st Period (7:07 PM EST),NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
1,22000001,4,10,0,1,7:07 PM,12:00,NaN,NaN,NaN,NaN,NaN,4.0,201599,DeAndre Jordan,1.610613e+09,Brooklyn,Nets,BKN,5,1630164,James Wiseman,1.610613e+09,Golden State,Warriors,GSW,2,1610612751,NaN,NaN,NaN,NaN,NaN,1
2,22000001,7,5,45,1,7:07 PM,11:50,Jordan Out of Bounds - Bad Pass Turnover Turnover (P1.T1),NaN,NaN,NaN,NaN,4.0,201599,DeAndre Jordan,1.610613e+09,Brooklyn,Nets,BKN,0,0,NaN,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN,NaN,1
3,22000001,8,6,2,1,7:07 PM,11:38,Irving S.FOUL (P1.T1) (S.Twardoski),NaN,NaN,NaN,NaN,4.0,202681,Kyrie Irving,1.610613e+09,Brooklyn,Nets,BKN,5,201939,Stephen Curry,1.610613e+09,Golden State,Warriors,GSW,1,0,NaN,NaN,NaN,NaN,NaN,1
4,22000001,10,3,11,1,7:08 PM,11:38,NaN,NaN,Curry Free Throw 1 of 2 (1 PTS),1 - 0,-1,5.0,201939,Stephen Curry,1.610613e+09,Golden State,Warriors,GSW,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2786254,22401230,722,3,11,4,11:15 PM,0:05,Gilgeous-Alexander Free Throw 1 of 2 (31 PTS),NaN,NaN,96 - 110,14,4.0,1628983,Shai Gilgeous-Alexander,1.610613e+09,Oklahoma City,Thunder,OKC,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
2786255,22401230,723,3,12,4,11:15 PM,0:05,Gilgeous-Alexander Free Throw 2 of 2 (32 PTS),NaN,NaN,96 - 111,15,4.0,1628983,Shai Gilgeous-Alexander,1.610613e+09,Oklahoma City,Thunder,OKC,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
2786256,22401230,724,2,79,4,11:16 PM,0:00,NaN,NaN,MISS Ja. Green 25' 3PT Pullup Jump Shot,NaN,NaN,5.0,1630224,Jalen Green,1.610613e+09,Houston,Rockets,HOU,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
2786257,22401230,725,4,0,4,11:16 PM,0:00,NaN,NaN,Rockets Rebound,NaN,NaN,3.0,1610612745,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
2786258,22401230,726,13,0,4,11:16 PM,0:00,NaN,End of 4th Period (11:16 PM EST),NaN,96 - 111,15,0.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1

In [93]:
nbastats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2786259 entries, 0 to 2786258
Data columns (total 34 columns):
 #   Column                     Dtype
---  ------                     -----
 0   GAME_ID                    int64
 1   EVENTNUM                   int64
 2   EVENTMSGTYPE               int64
 3   EVENTMSGACTIONTYPE         int64
 4   PERIOD                     int64
 5   WCTIMESTRING               object
 6   PCTIMESTRING               object
 7   HOMEDESCRIPTION            object
 8   NEUTRALDESCRIPTION         object
 9   VISITORDESCRIPTION         object
 10  SCORE                      object
 11  SCOREMARGIN                object
 12  PERSON1TYPE                float64
 13  PLAYER1_ID                 int64
 14  PLAYER1_NAME               object
 15  PLAYER1_TEAM_ID            float64
 16  PLAYER1_TEAM_CITY          object
 17  PLAYER1_TEAM_NICKNAME      object
 18  PLAYER1_TEAM_ABBREVIATION  object
 19  PERSON2TYPE                int64
 20  PLAYER2_ID                 int64
 21  PLAYER2_NAME               object
 22  PLAYER2_TEAM_ID            float64
 23  PLAYER2_TEAM_CITY          object
 24  PLAYER2_TEAM_NICKNAME      object
 25  PLAYER2_TEAM_ABBREVIATION  object
 26  PERSON3TYPE                int64
 27  PLAYER3_ID                 int64
 28  PLAYER3_NAME               object
 29  PLAYER3_TEAM_ID            float64
 30  PLAYER3_TEAM_CITY          object
 31  PLAYER3_TEAM_NICKNAME      object
 32  PLAYER3_TEAM_ABBREVIATION  object
 33  VIDEO_AVAILABLE_FLAG       int64
dtypes: float64(4), int64(11), object(19)
memory usage: 722.8+ MB

In [94]:
game_ids = nbastats['GAME_ID'].unique().tolist()
print(game_ids)
print(len(game_ids))

[22000001, 22000010, 22000100, 22001000, 22001001, 22001002, 22001003, 22001004, 22001005, 22001006, 22001007, 22001008, 22001009, 22000101, 22001010, 22001011, 22001012, 22001013, 22001014, 22001015, 22001016, 22001017, 22001018, 22001019, 22000102, 22001020, 22001021, 22001022, 22001023, 22001024, 22001025, 22001026, 22001027, 22001028, 22001029, 22000103, 22001030, 22001031, 22001032, 22001033, 22001034, 22001035, 22001036, 22001037, 22001038, 22001039, 22000104, 22001040, 22001041, 22001042, 22001043, 22001044, 22001045, 22001046, 22001047, 22001048, 22001049, 22000105, 22001050, 22001051, 22001052, 22001053, 22001054, 22001055, 22001056, 22001057, 22001058, 22001059, 22000106, 22001060, 22001061, 22001062, 22001063, 22001064, 22001065, 22001066, 22001067, 22001068, 22001069, 22000107, 22001070, 22001071, 22001072, 22001073, 22001074, 22001075, 22001076, 22001077, 22001078, 22001079, 22000108, 22001080, 22000109, 22000011, 22000110, 22000111, 22000112, 22000113, 22000114, 22000115, 22000116, 22000117, 22000118, 22000119, 22000012, 22000120, 22000121, 22000122, 22000123, 22000124, 22000125, 22000126, 22000127, 22000128, 22000129, 22000013, 22000130, 22000131, 22000132, 22000133, 22000134, 22000135, 22000136, 22000137, 22000138, 22000139, 22000014, 22000140, 22000141, 22000142, 22000143, 22000144, 22000145, 22000146, 22000147, 22000148, 22000149, 22000015, 22000150, 22000151, 22000152, 22000153, 22000154, 22000155, 22000156, 22000157, 22000158, 22000159, 22000016, 22000160, 22000161, 22000162, 22000163, 22000164, 22000165, 22000166, 22000167, 22000168, 22000169, 22000017, 22000170, 22000171, 22000172, 22000173, 22000174, 22000175, 22000176, 22000177, 22000178, 22000179, 22000018, 22000180, 22000181, 22000182, 22000183, 22000184, 22000185, 22000186, 22000187, 22000188, 22000189, 22000019, 22000190, 22000191, 22000192, 22000193, 22000194, 22000195, 22000196, 22000197, 22000198, 22000199, 22000002, 22000020, 22000200, 22000201, 22000202, 22000203, 22000204, 22000205, 22000206, 22000207, 22000208, 22000209, 22000021, 22000210, 22000211, 22000212, 22000213, 22000214, 22000215, 22000216, 22000217, 22000218, 22000219, 22000022, 22000220, 22000221, 22000222, 22000223, 22000224, 22000225, 22000226, 22000227, 22000228, 22000229, 22000023, 22000230, 22000231, 22000232, 22000233, 22000234, 22000235, 22000236, 22000237, 22000238, 22000239, 22000024, 22000240, 22000241, 22000242, 22000243, 22000244, 22000245, 22000246, 22000247, 22000248, 22000249, 22000025, 22000250, 22000251, 22000252, 22000253, 22000254, 22000255, 22000256, 22000257, 22000258, 22000259, 22000026, 22000260, 22000261, 22000262, 22000263, 22000264, 22000265, 22000266, 22000267, 22000268, 22000269, 22000027, 22000270, 22000271, 22000272, 22000273, 22000274, 22000275, 22000276, 22000277, 22000278, 22000279, 22000028, 22000280, 22000281, 22000282, 22000283, 22000284, 22000285, 22000286, 22000287, 22000288, 22000289, 22000029, 22000290, 22000291, 22000292, 22000293, 22000294, 22000295, 22000296, 22000297, 22000298, 22000299, 22000003, 22000030, 22000300, 22000301, 22000302, 22000303, 22000304, 22000305, 22000306, 22000307, 22000308, 22000309, 22000031, 22000310, 22000311, 22000312, 22000313, 22000314, 22000315, 22000316, 22000317, 22000318, 22000319, 22000032, 22000320, 22000321, 22000322, 22000323, 22000324, 22000325, 22000326, 22000327, 22000328, 22000329, 22000033, 22000330, 22000331, 22000332, 22000333, 22000334, 22000335, 22000336, 22000337, 22000338, 22000339, 22000034, 22000340, 22000341, 22000342, 22000343, 22000344, 22000345, 22000346, 22000347, 22000348, 22000349, 22000035, 22000350, 22000351, 22000352, 22000353, 22000354, 22000355, 22000356, 22000357, 22000358, 22000359, 22000036, 22000360, 22000361, 22000362, 22000363, 22000364, 22000365, 22000366, 22000367, 22000368, 22000369, 22000037, 22000370, 22000371, 22000372, 22000373, 22000374, 22000375, 22000376, 22000377, 22000378, 22000379, 22000038, 22000380, 22000381, 22000382, 22000383, 22000384, 22000385, 22000386, 22000387, 22000388, 22000389, 22000039, 22000390, 22000391, 22000392, 22000393, 22000394, 22000395, 22000396, 22000397, 22000398, 22000399, 22000004, 22000040, 22000400, 22000401, 22000402, 22000403, 22000404, 22000405, 22000406, 22000407, 22000408, 22000409, 22000041, 22000410, 22000411, 22000412, 22000413, 22000414, 22000415, 22000416, 22000417, 22000418, 22000419, 22000042, 22000420, 22000421, 22000422, 22000423, 22000424, 22000425, 22000426, 22000427, 22000428, 22000429, 22000043, 22000430, 22000431, 22000432, 22000433, 22000434, 22000435, 22000436, 22000437, 22000438, 22000439, 22000044, 22000440, 22000441, 22000442, 22000443, 22000444, 22000445, 22000446, 22000447, 22000448, 22000449, 22000045, 22000450, 22000451, 22000452, 22000453, 22000454, 22000455, 22000456, 22000457, 22000458, 22000459, 22000046, 22000460, 22000461, 22000462, 22000463, 22000464, 22000465, 22000466, 22000467, 22000468, 22000469, 22000047, 22000470, 22000471, 22000472, 22000473, 22000474, 22000475, 22000476, 22000477, 22000478, 22000479, 22000048, 22000480, 22000481, 22000482, 22000483, 22000484, 22000485, 22000486, 22000487, 22000488, 22000489, 22000049, 22000490, 22000491, 22000492, 22000493, 22000494, 22000495, 22000496, 22000497, 22000498, 22000499, 22000005, 22000050, 22000500, 22000501, 22000502, 22000503, 22000504, 22000505, 22000506, 22000507, 22000508, 22000509, 22000051, 22000510, 22000511, 22000512, 22000513, 22000514, 22000515, 22000516, 22000517, 22000518, 22000519, 22000052, 22000520, 22000521, 22000522, 22000523, 22000524, 22000525, 22000526, 22000527, 22000528, 22000529, 22000053, 22000530, 22000531, 22000532, 22000533, 22000534, 22000535, 22000536, 22000537, 22000538, 22000539, 22000054, 22000540, 22000541, 22000542, 22000543, 22000544, 22000545, 22000546, 22000547, 22000548, 22000549, 22000055, 22000550, 22000551, 22000552, 22000553, 22000554, 22000555, 22000556, 22000557, 22000558, 22000559, 22000056, 22000560, 22000561, 22000562, 22000563, 22000564, 22000565, 22000566, 22000567, 22000568, 22000569, 22000057, 22000570, 22000571, 22000572, 22000573, 22000574, 22000575, 22000576, 22000577, 22000578, 22000579, 22000058, 22000580, 22000581, 22000582, 22000583, 22000584, 22000585, 22000586, 22000587, 22000588, 22000589, 22000059, 22000590, 22000591, 22000592, 22000593, 22000594, 22000595, 22000596, 22000597, 22000598, 22000599, 22000006, 22000060, 22000600, 22000601, 22000602, 22000603, 22000604, 22000605, 22000606, 22000607, 22000608, 22000609, 22000061, 22000610, 22000611, 22000612, 22000613, 22000614, 22000615, 22000616, 22000617, 22000618, 22000619, 22000062, 22000620, 22000621, 22000622, 22000623, 22000624, 22000625, 22000626, 22000627, 22000628, 22000629, 22000063, 22000630, 22000631, 22000632, 22000633, 22000634, 22000635, 22000636, 22000637, 22000638, 22000639, 22000064, 22000640, 22000641, 22000642, 22000643, 22000644, 22000645, 22000646, 22000647, 22000648, 22000649, 22000065, 22000650, 22000651, 22000652, 22000653, 22000654, 22000655, 22000656, 22000657, 22000658, 22000659, 22000066, 22000660, 22000661, 22000662, 22000663, 22000664, 22000665, 22000666, 22000667, 22000668, 22000669, 22000067, 22000670, 22000671, 22000672, 22000673, 22000674, 22000675, 22000676, 22000677, 22000678, 22000679, 22000068, 22000680, 22000681, 22000682, 22000683, 22000684, 22000685, 22000686, 22000687, 22000688, 22000689, 22000069, 22000690, 22000691, 22000692, 22000693, 22000694, 22000695, 22000696, 22000697, 22000698, 22000699, 22000007, 22000070, 22000700, 22000701, 22000702, 22000703, 22000704, 22000705, 22000706, 22000707, 22000708, 22000709, 22000071, 22000710, 22000711, 22000712, 22000713, 22000714, 22000715, 22000716, 22000717, 22000718, 22000719, 22000072, 22000720, 22000721, 22000722, 22000723, 22000724, 22000725, 22000726, 22000727, 22000728, 22000729, 22000073, 22000730, 22000731, 22000732, 22000733, 22000734, 22000735, 22000736, 22000737, 22000738, 22000739, 22000074, 22000740, 22000741, 22000742, 22000743, 22000744, 22000745, 22000746, 22000747, 22000748, 22000749, 22000075, 22000750, 22000751, 22000752, 22000753, 22000754, 22000755, 22000756, 22000757, 22000758, 22000759, 22000076, 22000760, 22000761, 22000762, 22000763, 22000764, 22000765, 22000766, 22000767, 22000768, 22000769, 22000077, 22000770, 22000771, 22000772, 22000773, 22000774, 22000775, 22000776, 22000777, 22000778, 22000779, 22000078, 22000780, 22000781, 22000782, 22000783, 22000784, 22000785, 22000786, 22000787, 22000788, 22000789, 22000079, 22000790, 22000791, 22000792, 22000793, 22000794, 22000795, 22000796, 22000797, 22000798, 22000799, 22000008, 22000080, 22000800, 22000801, 22000802, 22000803, 22000804, 22000805, 22000806, 22000807, 22000808, 22000809, 22000081, 22000810, 22000811, 22000812, 22000813, 22000814, 22000815, 22000816, 22000817, 22000818, 22000819, 22000082, 22000820, 22000821, 22000822, 22000823, 22000824, 22000825, 22000826, 22000827, 22000828, 22000829, 22000083, 22000830, 22000831, 22000832, 22000833, 22000834, 22000835, 22000836, 22000837, 22000838, 22000839, 22000084, 22000840, 22000841, 22000842, 22000843, 22000844, 22000845, 22000846, 22000847, 22000848, 22000849, 22000085, 22000850, 22000851, 22000852, 22000853, 22000854, 22000855, 22000856, 22000857, 22000858, 22000859, 22000086, 22000860, 22000861, 22000862, 22000863, 22000864, 22000865, 22000866, 22000867, 22000868, 22000869, 22000087, 22000870, 22000871, 22000872, 22000873, 22000874, 22000875, 22000876, 22000877, 22000878, 22000879, 22000088, 22000880, 22000881, 22000882, 22000883, 22000884, 22000885, 22000886, 22000887, 22000888, 22000889, 22000089, 22000890, 22000891, 22000892, 22000893, 22000894, 22000895, 22000896, 22000897, 22000898, 22000899, 22000009, 22000090, 22000900, 22000901, 22000902, 22000903, 22000904, 22000905, 22000906, 22000907, 22000908, 22000909, 22000091, 22000910, 22000911, 22000912, 22000913, 22000914, 22000915, 22000916, 22000917, 22000918, 22000919, 22000092, 22000920, 22000921, 22000922, 22000923, 22000924, 22000925, 22000926, 22000927, 22000928, 22000929, 22000093, 22000930, 22000931, 22000932, 22000933, 22000934, 22000935, 22000936, 22000937, 22000938, 22000939, 22000094, 22000940, 22000941, 22000942, 22000943, 22000944, 22000945, 22000946, 22000947, 22000948, 22000949, 22000095, 22000950, 22000951, 22000952, 22000953, 22000954, 22000955, 22000956, 22000957, 22000958, 22000959, 22000096, 22000960, 22000961, 22000962, 22000963, 22000964, 22000965, 22000966, 22000967, 22000968, 22000969, 22000097, 22000970, 22000971, 22000972, 22000973, 22000974, 22000975, 22000976, 22000977, 22000978, 22000979, 22000098, 22000980, 22000981, 22000982, 22000983, 22000984, 22000985, 22000986, 22000987, 22000988, 22000989, 22000099, 22000990, 22000991, 22000992, 22000993, 22000994, 22000995, 22000996, 22000997, 22000998, 22000999, 22100001, 22100010, 22100100, 22101000, 22101001, 22101002, 22101003, 22101004, 22101005, 22101006, 22101007, 22101008, 22101009, 22100101, 22101010, 22101011, 22101012, 22101013, 22101014, 22101015, 22101016, 22101017, 22101018, 22101019, 22100102, 22101020, 22101021, 22101022, 22101023, 22101024, 22101025, 22101026, 22101027, 22101028, 22101029, 22100103, 22101030, 22101031, 22101032, 22101033, 22101034, 22101035, 22101036, 22101037, 22101038, 22101039, 22100104, 22101040, 22101041, 22101042, 22101043, 22101044, 22101045, 22101046, 22101047, 22101048, 22101049, 22100105, 22101050, 22101051, 22101052, 22101053, 22101054, 22101055, 22101056, 22101057, 22101058, 22101059, 22100106, 22101060, 22101061, 22101062, 22101063, 22101064, 22101065, 22101066, 22101067, 22101068, 22101069, 22100107, 22101070, 22101071, 22101072, 22101073, 22101074, 22101075, 22101076, 22101077, 22101078, 22101079, 22100108, 22101080, 22101081, 22101082, 22101083, 22101084, 22101085, 22101086, 22101087, 22101088, 22101089, 22100109, 22101090, 22101091, 22101092, 22101093, 22101094, 22101095, 22101096, 22101097, 22101098, 22101099, 22100011, 22100110, 22101100, 22101101, 22101102, 22101103, 22101104, 22101105, 22101106, 22101107, 22101108, 22101109, 22100111, 22101110, 22101111, 22101112, 22101113, 22101114, 22101115, 22101116, 22101117, 22101118, 22101119, 22100112, 22101120, 22101121, 22101122, 22101123, 22101124, 22101125, 22101126, 22101127, 22101128, 22101129, 22100113, 22101130, 22101131, 22101132, 22101133, 22101134, 22101135, 22101136, 22101137, 22101138, 22101139, 22100114, 22101140, 22101141, 22101142, 22101143, 22101144, 22101145, 22101146, 22101147, 22101148, 22101149, 22100115, 22101150, 22101151, 22101152, 22101153, 22101154, 22101155, 22101156, 22101157, 22101158, 22101159, 22100116, 22101160, 22101161, 22101162, 22101163, 22101164, 22101165, 22101166, 22101167, 22101168, 22101169, 22100117, 22101170, 22101171, 22101172, 22101173, 22101174, 22101175, 22101176, 22101177, 22101178, 22101179, 22100118, 22101180, 22101181, 22101182, 22101183, 22101184, 22101185, 22101186, 22101187, 22101188, 22101189, 22100119, 22101190, 22101191, 22101192, 22101193, 22101194, 22101195, 22101196, 22101197, 22101198, 22101199, 22100012, 22100120, 22101200, 22101201, 22101202, 22101203, 22101204, 22101205, 22101206, 22101207, 22101208, 22101209, 22100121, 22101210, 22101211, 22101212, 22101213, 22101214, 22101215, 22101216, 22101217, 22101218, 22101219, 22100122, 22101220, 22101221, 22101222, 22101223, 22101224, 22101225, 22101226, 22101227, 22101228, 22101229, 22100123, 22101230, 22100124, 22100125, 22100126, 22100127, 22100128, 22100129, 22100013, 22100130, 22100131, 22100132, 22100133, 22100134, 22100135, 22100136, 22100137, 22100138, 22100139, 22100014, 22100140, 22100141, 22100142, 22100143, 22100144, 22100145, 22100146, 22100147, 22100148, 22100149, 22100015, 22100150, 22100151, 22100152, 22100153, 22100154, 22100155, 22100156, 22100157, 22100158, 22100159, 22100016, 22100160, 22100161, 22100162, 22100163, 22100164, 22100165, 22100166, 22100167, 22100168, 22100169, 22100017, 22100170, 22100171, 22100172, 22100173, 22100174, 22100175, 22100176, 22100177, 22100178, 22100179, 22100018, 22100180, 22100181, 22100182, 22100183, 22100184, 22100185, 22100186, 22100187, 22100188, 22100189, 22100019, 22100190, 22100191, 22100192, 22100193, 22100194, 22100195, 22100196, 22100197, 22100198, 22100199, 22100002, 22100020, 22100200, 22100201, 22100202, 22100203, 22100204, 22100205, 22100206, 22100207, 22100208, 22100209, 22100021, 22100210, 22100211, 22100212, 22100213, 22100214, 22100215, 22100216, 22100217, 22100218, 22100219, 22100022, 22100220, 22100221, 22100222, 22100223, 22100224, 22100225, 22100226, 22100227, 22100228, 22100229, 22100023, 22100230, 22100231, 22100232, 22100233, 22100234, 22100235, 22100236, 22100237, 22100238, 22100239, 22100024, 22100240, 22100241, 22100242, 22100243, 22100244, 22100245, 22100246, 22100247, 22100248, 22100249, 22100025, 22100250, 22100251, 22100252, 22100253, 22100254, 22100255, 22100256, 22100257, 22100258, 22100259, 22100026, 22100260, 22100261, 22100262, 22100263, 22100264, 22100265, 22100266, 22100267, 22100268, 22100269, 22100027, 22100270, 22100271, 22100272, 22100273, 22100274, 22100275, 22100276, 22100277, 22100278, 22100279, 22100028, 22100280, 22100281, 22100282, 22100283, 22100284, 22100285, 22100286, 22100287, 22100288, 22100289, 22100029, 22100290, 22100291, 22100292, 22100293, 22100294, 22100295, 22100296, 22100297, 22100298, 22100299, 22100003, 22100030, 22100300, 22100301, 22100302, 22100303, 22100304, 22100305, 22100306, 22100307, 22100308, 22100309, 22100031, 22100310, 22100311, 22100312, 22100313, 22100314, 22100315, 22100316, 22100317, 22100318, 22100319, 22100032, 22100320, 22100321, 22100322, 22100323, 22100324, 22100325, 22100326, 22100327, 22100328, 22100329, 22100033, 22100330, 22100331, 22100332, 22100333, 22100334, 22100335, 22100336, 22100337, 22100338, 22100339, 22100034, 22100340, 22100341, 22100342, 22100343, 22100344, 22100345, 22100346, 22100347, 22100348, 22100349, 22100035, 22100350, 22100351, 22100352, 22100353, 22100354, 22100355, 22100356, 22100357, 22100358, 22100359, 22100036, 22100360, 22100361, 22100362, 22100363, 22100364, 22100365, 22100366, 22100367, 22100368, 22100369, 22100037, 22100370, 22100371, 22100372, 22100373, 22100374, 22100375, 22100376, 22100377, 22100378, 22100379, 22100038, 22100380, 22100381, 22100382, 22100383, 22100384, 22100385, 22100386, 22100387, 22100388, 22100389, 22100039, 22100390, 22100391, 22100392, 22100393, 22100394, 22100395, 22100396, 22100397, 22100398, 22100399, 22100004, 22100040, 22100400, 22100401, 22100402, 22100403, 22100404, 22100405, 22100406, 22100407, 22100408, 22100409, 22100041, 22100410, 22100411, 22100412, 22100413, 22100414, 22100415, 22100416, 22100417, 22100418, 22100419, 22100042, 22100420, 22100421, 22100422, 22100423, 22100424, 22100425, 22100426, 22100427, 22100428, 22100429, 22100043, 22100430, 22100431, 22100432, 22100433, 22100434, 22100435, 22100436, 22100437, 22100438, 22100439, 22100044, 22100440, 22100441, 22100442, 22100443, 22100444, 22100445, 22100446, 22100447, 22100448, 22100449, 22100045, 22100450, 22100451, 22100452, 22100453, 22100454, 22100455, 22100456, 22100457, 22100458, 22100459, 22100046, 22100460, 22100461, 22100462, 22100463, 22100464, 22100465, 22100466, 22100467, 22100468, 22100469, 22100047, 22100470, 22100471, 22100472, 22100473, 22100474, 22100475, 22100476, 22100477, 22100478, 22100479, 22100048, 22100480, 22100481, 22100482, 22100483, 22100484, 22100485, 22100486, 22100487, 22100488, 22100489, 22100049, 22100490, 22100491, 22100492, 22100493, 22100494, 22100495, 22100496, 22100497, 22100498, 22100499, 22100005, 22100050, 22100500, 22100501, 22100502, 22100503, 22100504, 22100505, 22100506, 22100507, 22100508, 22100509, 22100051, 22100510, 22100511, 22100512, 22100513, 22100514, 22100515, 22100516, 22100517, 22100518, 22100519, 22100052, 22100520, 22100521, 22100522, 22100523, 22100524, 22100525, 22100526, 22100527, 22100528, 22100529, 22100053, 22100530, 22100531, 22100532, 22100533, 22100534, 22100535, 22100536, 22100537, 22100538, 22100539, 22100054, 22100540, 22100541, 22100542, 22100543, 22100544, 22100545, 22100546, 22100547, 22100548, 22100549, 22100055, 22100550, 22100551, 22100552, 22100553, 22100554, 22100555, 22100556, 22100557, 22100558, 22100559, 22100056, 22100560, 22100561, 22100562, 22100563, 22100564, 22100565, 22100566, 22100567, 22100568, 22100569, 22100057, 22100570, 22100571, 22100572, 22100573, 22100574, 22100575, 22100576, 22100577, 22100578, 22100579, 22100058, 22100580, 22100581, 22100582, 22100583, 22100584, 22100585, 22100586, 22100587, 22100588, 22100589, 22100059, 22100590, 22100591, 22100592, 22100593, 22100594, 22100595, 22100596, 22100597, 22100598, 22100599, 22100006, 22100060, 22100600, 22100601, 22100602, 22100603, 22100604, 22100605, 22100606, 22100607, 22100608, 22100609, 22100061, 22100610, 22100611, 22100612, 22100613, 22100614, 22100615, 22100616, 22100617, 22100618, 22100619, 22100062, 22100620, 22100621, 22100622, 22100623, 22100624, 22100625, 22100626, 22100627, 22100628, 22100629, 22100063, 22100630, 22100631, 22100632, 22100633, 22100634, 22100635, 22100636, 22100637, 22100638, 22100639, 22100064, 22100640, 22100641, 22100642, 22100643, 22100644, 22100645, 22100646, 22100647, 22100648, 22100649, 22100065, 22100650, 22100651, 22100652, 22100653, 22100654, 22100655, 22100656, 22100657, 22100658, 22100659, 22100066, 22100660, 22100661, 22100662, 22100663, 22100664, 22100665, 22100666, 22100667, 22100668, 22100669, 22100067, 22100670, 22100671, 22100672, 22100673, 22100674, 22100675, 22100676, 22100677, 22100678, 22100679, 22100068, 22100680, 22100681, 22100682, 22100683, 22100684, 22100685, 22100686, 22100687, 22100688, 22100689, 22100069, 22100690, 22100691, 22100692, 22100693, 22100694, 22100695, 22100696, 22100697, 22100698, 22100699, 22100007, 22100070, 22100700, 22100701, 22100702, 22100703, 22100704, 22100705, 22100706, 22100707, 22100708, 22100709, 22100071, 22100710, 22100711, 22100712, 22100713, 22100714, 22100715, 22100716, 22100717, 22100718, 22100719,

In [95]:
game = nbastats.loc[nbastats['GAME_ID'] == 22000010].reset_index().drop(columns='index')
game

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,22000010,2,12,0,1,7:11 PM,12:00,NaN,Start of 1st Period (7:11 PM EST),NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
1,22000010,4,10,0,1,7:11 PM,12:00,Jump Ball Drummond vs. Zeller: Tip to Rozier,NaN,NaN,NaN,NaN,4.0,203083,Andre Drummond,1.610613e+09,Cleveland,Cavaliers,CLE,5,203469,Cody Zeller,1.610613e+09,Charlotte,Hornets,CHA,5,1626179,Terry Rozier,1.610613e+09,Charlotte,Hornets,CHA,1
2,22000010,7,2,79,1,7:12 PM,11:43,NaN,NaN,MISS Graham 26' 3PT Pullup Jump Shot,NaN,NaN,5.0,1628984,Devonte' Graham,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
3,22000010,8,4,0,1,7:12 PM,11:41,Drummond REBOUND (Off:0 Def:1),NaN,NaN,NaN,NaN,4.0,203083,Andre Drummond,1.610613e+09,Cleveland,Cavaliers,CLE,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
4,22000010,9,5,1,1,7:12 PM,11:25,Drummond Bad Pass Turnover (P1.T1),NaN,Zeller STEAL (1 STL),NaN,NaN,4.0,203083,Andre Drummond,1.610613e+09,Cleveland,Cavaliers,CLE,5,203469,Cody Zeller,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,22000010,702,8,0,4,9:23 PM,0:08,SUB: Okoro FOR Osman,NaN,NaN,NaN,NaN,4.0,1626224,Cedi Osman,1.610613e+09,Cleveland,Cavaliers,CLE,4,1630171,Isaac Okoro,1.610613e+09,Cleveland,Cavaliers,CLE,0,0,NaN,NaN,NaN,NaN,NaN,0
463,22000010,704,3,12,4,9:23 PM,0:08,Sexton Free Throw 2 of 2 (27 PTS),NaN,NaN,114 - 121,7,4.0,1629012,Collin Sexton,1.610613e+09,Cleveland,Cavaliers,CLE,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
464,22000010,705,2,1,4,9:23 PM,0:01,NaN,NaN,MISS Graham 28' 3PT Jump Shot,NaN,NaN,5.0,1628984,Devonte' Graham,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
465,22000010,706,4,0,4,9:23 PM,0:01,NaN,NaN,Hornets Rebound,NaN,NaN,3.0,1610612766,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
466,22000010,707,13,0,4,9:23 PM,0:00,NaN,End of 4th Period (9:23 PM EST),NaN,114 - 121,7,0.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1

In [100]:
def one_game_on_court(x):
    game_ = nbastats.loc[nbastats['GAME_ID'] == x].reset_index().drop(columns='index')
    if game_.empty:
        print(f"Warning: No rows found for GAME_ID {x}")
        return pd.DataFrame()  # Return empty DataFrame
    try:
        df = noc.players_on_court(game_)
    except Exception as e:
        print(f"ReadTimeout or other error for GAME_ID {x}: {e}")
        return pd.DataFrame()
    if df.empty:
        print(f"Warning: noc.players_on_court returned empty for GAME_ID {x}")
    return df



for game in game_ids:
    df = one_game_on_court(game)
    if not df.empty:
        on_court_stats = pd.concat([on_court_stats, df], ignore_index=True)
    else:
        print(f"Warning: No data for GAME_ID {game}")

ReadTimeout or other error for GAME_ID 22000100: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000100
ReadTimeout or other error for GAME_ID 22001012: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22001012
ReadTimeout or other error for GAME_ID 22001038: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22001038
ReadTimeout or other error for GAME_ID 22001064: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22001064
ReadTimeout or other error for GAME_ID 22000120: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000120
ReadTimeout or other error for GAME_ID 22000138: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000138
ReadTimeout or other error for GAME_ID 22000023: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000023
ReadTimeout or other error for GAME_ID 22000356: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000356
ReadTimeout or other error for GAME_ID 22000387: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000387
ReadTimeout or other error for GAME_ID 22000440: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000440
ReadTimeout or other error for GAME_ID 22000465: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000465
ReadTimeout or other error for GAME_ID 22000485: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000485
ReadTimeout or other error for GAME_ID 22000490: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000490
ReadTimeout or other error for GAME_ID 22000577: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000577
ReadTimeout or other error for GAME_ID 22000582: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000582
ReadTimeout or other error for GAME_ID 22000059: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000059
ReadTimeout or other error for GAME_ID 22000637: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000637
ReadTimeout or other error for GAME_ID 22000645: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000645
ReadTimeout or other error for GAME_ID 22000681: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000681
ReadTimeout or other error for GAME_ID 22000695: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000695
ReadTimeout or other error for GAME_ID 22000751: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000751
ReadTimeout or other error for GAME_ID 22000847: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000847
ReadTimeout or other error for GAME_ID 22000901: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000901
ReadTimeout or other error for GAME_ID 22000934: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000934
ReadTimeout or other error for GAME_ID 22000951: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000951
ReadTimeout or other error for GAME_ID 22000973: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22000973
ReadTimeout or other error for GAME_ID 22101010: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22101010
ReadTimeout or other error for GAME_ID 22101149: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22101149
ReadTimeout or other error for GAME_ID 22100126: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100126
ReadTimeout or other error for GAME_ID 22100266: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100266
ReadTimeout or other error for GAME_ID 22100274: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100274
ReadTimeout or other error for GAME_ID 22100283: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100283
ReadTimeout or other error for GAME_ID 22100291: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100291
ReadTimeout or other error for GAME_ID 22100297: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100297
ReadTimeout or other error for GAME_ID 22100353: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100353
ReadTimeout or other error for GAME_ID 22100359: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100359
ReadTimeout or other error for GAME_ID 22100041: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100041
ReadTimeout or other error for GAME_ID 22100413: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100413
ReadTimeout or other error for GAME_ID 22100479: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100479
ReadTimeout or other error for GAME_ID 22100555: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100555
ReadTimeout or other error for GAME_ID 22100602: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100602
ReadTimeout or other error for GAME_ID 22100678: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100678
ReadTimeout or other error for GAME_ID 22100688: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100688
ReadTimeout or other error for GAME_ID 22100074: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100074
ReadTimeout or other error for GAME_ID 22100748: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100748
ReadTimeout or other error for GAME_ID 22100774: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100774
ReadTimeout or other error for GAME_ID 22100778: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100778
ReadTimeout or other error for GAME_ID 22100787: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100787
ReadTimeout or other error for GAME_ID 22100860: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100860
ReadTimeout or other error for GAME_ID 22100935: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100935
ReadTimeout or other error for GAME_ID 22100967: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22100967
ReadTimeout or other error for GAME_ID 22201007: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201007
ReadTimeout or other error for GAME_ID 22201040: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201040
ReadTimeout or other error for GAME_ID 22200107: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200107
ReadTimeout or other error for GAME_ID 22201122: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201122
ReadTimeout or other error for GAME_ID 22201161: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201161
ReadTimeout or other error for GAME_ID 22200117: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200117
ReadTimeout or other error for GAME_ID 22201170: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201170
ReadTimeout or other error for GAME_ID 22201194: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201194
ReadTimeout or other error for GAME_ID 22201205: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22201205
ReadTimeout or other error for GAME_ID 22200140: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200140
ReadTimeout or other error for GAME_ID 22200186: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200186
ReadTimeout or other error for GAME_ID 22200234: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200234
ReadTimeout or other error for GAME_ID 22200235: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200235
ReadTimeout or other error for GAME_ID 22200025: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200025
ReadTimeout or other error for GAME_ID 22200325: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200325
ReadTimeout or other error for GAME_ID 22200328: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200328
ReadTimeout or other error for GAME_ID 22200331: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200331
ReadTimeout or other error for GAME_ID 22200344: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200344
ReadTimeout or other error for GAME_ID 22200039: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200039
ReadTimeout or other error for GAME_ID 22200040: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200040
ReadTimeout or other error for GAME_ID 22200400: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200400
ReadTimeout or other error for GAME_ID 22200410: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200410
ReadTimeout or other error for GAME_ID 22200413: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200413
ReadTimeout or other error for GAME_ID 22200440: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200440
ReadTimeout or other error for GAME_ID 22200519: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200519
ReadTimeout or other error for GAME_ID 22200552: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200552
ReadTimeout or other error for GAME_ID 22200659: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200659
ReadTimeout or other error for GAME_ID 22200072: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200072
ReadTimeout or other error for GAME_ID 22200748: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200748
ReadTimeout or other error for GAME_ID 22200758: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200758
ReadTimeout or other error for GAME_ID 22200761: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200761
ReadTimeout or other error for GAME_ID 22200765: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200765
ReadTimeout or other error for GAME_ID 22200082: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200082
ReadTimeout or other error for GAME_ID 22200854: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200854
ReadTimeout or other error for GAME_ID 22200892: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200892
ReadTimeout or other error for GAME_ID 22200924: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200924
ReadTimeout or other error for GAME_ID 22200956: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22200956
ReadTimeout or other error for GAME_ID 22300029: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300029
ReadTimeout or other error for GAME_ID 22300128: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300128
ReadTimeout or other error for GAME_ID 22300162: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300162
ReadTimeout or other error for GAME_ID 22300165: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300165
ReadTimeout or other error for GAME_ID 22300214: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300214
ReadTimeout or other error for GAME_ID 22300264: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300264
ReadTimeout or other error for GAME_ID 22300289: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300289
ReadTimeout or other error for GAME_ID 22300291: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300291
ReadTimeout or other error for GAME_ID 22300300: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300300
ReadTimeout or other error for GAME_ID 22300323: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300323
ReadTimeout or other error for GAME_ID 22300349: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300349
ReadTimeout or other error for GAME_ID 22300473: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300473
ReadTimeout or other error for GAME_ID 22300499: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300499
ReadTimeout or other error for GAME_ID 22300517: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300517
ReadTimeout or other error for GAME_ID 22300668: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300668
ReadTimeout or other error for GAME_ID 22300710: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300710
ReadTimeout or other error for GAME_ID 22300712: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300712
ReadTimeout or other error for GAME_ID 22300810: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300810
ReadTimeout or other error for GAME_ID 22300827: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300827
ReadTimeout or other error for GAME_ID 22300849: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300849
ReadTimeout or other error for GAME_ID 22300856: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300856
ReadTimeout or other error for GAME_ID 22300868: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300868
ReadTimeout or other error for GAME_ID 22300893: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300893
ReadTimeout or other error for GAME_ID 22300898: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300898
ReadTimeout or other error for GAME_ID 22300919: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300919
ReadTimeout or other error for GAME_ID 22300989: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)
Warning: No data for GAME_ID 22300989
ReadTimeout or other error for GAME_ID 22301060: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=10)

In [103]:
on_court_stats

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,AWAY_PLAYER1,AWAY_PLAYER2,AWAY_PLAYER3,AWAY_PLAYER4,AWAY_PLAYER5,HOME_PLAYER1,HOME_PLAYER2,HOME_PLAYER3,HOME_PLAYER4,HOME_PLAYER5
0,22000001,2,12,0,1,7:07 PM,0,NaN,Start of 1st Period (7:07 PM EST),NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,201939,203952,1630164,1629672,1626162,202681,201599,203915,203925,201142
1,22000001,4,10,0,1,7:07 PM,0,NaN,NaN,NaN,NaN,NaN,4.0,201599,DeAndre Jordan,1.610613e+09,Brooklyn,Nets,BKN,5,1630164,James Wiseman,1.610613e+09,Golden State,Warriors,GSW,2,1610612751,NaN,NaN,NaN,NaN,NaN,1,201939,203952,1630164,1629672,1626162,202681,201599,203915,203925,201142
2,22000001,7,5,45,1,7:07 PM,10,Jordan Out of Bounds - Bad Pass Turnover Turnover (P1.T1),NaN,NaN,NaN,NaN,4.0,201599,DeAndre Jordan,1.610613e+09,Brooklyn,Nets,BKN,0,0,NaN,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN,NaN,1,201939,203952,1630164,1629672,1626162,202681,201599,203915,203925,201142
3,22000001,8,6,2,1,7:07 PM,22,Irving S.FOUL (P1.T1) (S.Twardoski),NaN,NaN,NaN,NaN,4.0,202681,Kyrie Irving,1.610613e+09,Brooklyn,Nets,BKN,5,201939,Stephen Curry,1.610613e+09,Golden State,Warriors,GSW,1,0,NaN,NaN,NaN,NaN,NaN,1,201939,203952,1630164,1629672,1626162,202681,201599,203915,203925,201142
4,22000001,10,3,11,1,7:08 PM,22,NaN,NaN,Curry Free Throw 1 of 2 (1 PTS),1 - 0,-1,5.0,201939,Stephen Curry,1.610613e+09,Golden State,Warriors,GSW,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1,201939,203952,1630164,1629672,1626162,202681,201599,203915,203925,201142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2765339,22401230,722,3,11,4,11:15 PM,2875,Gilgeous-Alexander Free Throw 1 of 2 (31 PTS),NaN,NaN,96 - 110,14,4.0,1628983,Shai Gilgeous-Alexander,1.610613e+09,Oklahoma City,Thunder,OKC,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1,1631095,1628415,1630224,1627832,1630578,1641717,1628983,1631114,1629652,1627936
2765340,22401230,723,3,12,4,11:15 PM,2875,Gilgeous-Alexander Free Throw 2 of 2 (32 PTS),NaN,NaN,96 - 111,15,4.0,1628983,Shai Gilgeous-Alexander,1.610613e+09,Oklahoma City,Thunder,OKC,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1,1631095,1628415,1630224,1627832,1630578,1641717,1628983,1631114,1629652,1627936
2765341,22401230,724,2,79,4,11:16 PM,2880,NaN,NaN,MISS Ja. Green 25' 3PT Pullup Jump Shot,NaN,NaN,5.0,1630224,Jalen Green,1.610613e+09,Houston,Rockets,HOU,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1,1631095,1628415,1630224,1627832,1630578,1641717,1628983,1631114,1629652,1627936
2765342,22401230,725,4,0,4,11:16 PM,2880,NaN,NaN,Rockets Rebound,NaN,NaN,3.0,1610612745,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,1631095,1628415,1630224,1627832,1630578,1641717,1628983,1631114,1629652,1627936
2765343,22401230,726,13,0,4,11:16 PM,2880,NaN,End of 4th Period (11:16 PM EST),NaN,96 - 111,15,0.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1,1631095,1628415,1630224,1627832,1630578,1641717,1628983,1631114,1629652,1627936

In [105]:
on_court_stats.to_csv('nba_data.csv')

#nbastats = noc.players_on_court(nbastats)